In [81]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

In [82]:
#create the variable that stores the decision tree
clf = DecisionTreeClassifier()

In [83]:
#store the training data and solution data 
#into dataframes and then factorize the strings into
#integers for the classifier to use
d = {"Weight": [140,130,150,170],"Skin" : [0,0,1,1]}
p = {"Fruit" : [0,0,1,1]}
X = pd.DataFrame(data = d)
X
y = pd.DataFrame(data=p)


In [84]:
clf.fit(X,y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [85]:
d = {"Weight": [140],"Skin" : [1]}
X = pd.DataFrame(data = d)
clf.predict(X)

array([1], dtype=int64)

In [86]:
d = {"Weight": [125],"Skin" : [0]}
X = pd.DataFrame(data = d)
clf.predict(X)

array([0], dtype=int64)

In [87]:
d = {"Weight": [140],"Skin" : [0]}
X = pd.DataFrame(data = d)
clf.predict(X)

array([0], dtype=int64)

In [88]:
d = {"Weight": [110],"Skin" : [1]}
X = pd.DataFrame(data = d)
clf.predict(X)

array([1], dtype=int64)

In [89]:
# the skin is more important than the weight because the
# same weight is tested for each skin and the label changes
# with the skin description

In [100]:
Gender = [0,0,1,0,1,1]
Age = [15,25,32,40,12,14]
App = [1,2,3,2,1,1]
d={'Gender':Gender,'Age':Age}
p={'App':App}

In [101]:
X = pd.DataFrame(data=d)
y = pd.DataFrame(data=p)

In [102]:
clf2 = DecisionTreeClassifier()

In [103]:
clf2.fit(X,y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [104]:
d = {'Gender': [1],'Age': [21]}
X = pd.DataFrame(data = d)
clf2.predict(X)
#output is 3 so the App would be Snapchat

array([3], dtype=int64)

In [105]:
d = {'Gender': [0],'Age': [18]}
X = pd.DataFrame(data = d)
clf2.predict(X)
#output is 1 so the App would be Pokemon Go

array([1], dtype=int64)